version: '2'
services:
  mongo:
    image: mongo:latest
    volumes:
      - ./data/mongo:/data/db
  elasticsearch:
    image: elasticsearch:latest
    command: "elasticsearch -Des.cluster.name='graylog'"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
  server:
    image: graylog2/server:latest
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_REST_TRANSPORT_URI: http://127.0.0.1:12900
    links:
      - mongo
      - elasticsearch
    ports:
      - 9000:9000
      - 12900:12900
      - 12201:12201/tcp
      - 12201:12201/udp
    volumes:
      - ./data/graylog/journal:/usr/share/graylog/data/journal    
